package com.joeyos.app.data

import com.joeyos.app.AppLog
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.apache.commons.compress.archivers.sevenz.SevenZFile
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.net.URLEncoder
import java.util.concurrent.ConcurrentHashMap
import java.util.zip.CRC32
import java.util.zip.ZipFile
import java.util.zip.ZipInputStream

/** One romhack that can be applied to a base ROM, from the RetroAchievements patch set. */
data class RaHack(
    val name: String,
    /** Hack, Translation or Fix. */
    val type: String,
    /** Path within the RAPatches repo, fetched from raw at apply time. */
    val path: String,
    /** bps, ips or xdelta, so the patcher knows how to read it. */
    val format: String,
)

/**
 * RetroAchievements romhack patches, matched to the user's own ROMs by checksum. Ported from
 * Chameleon. The index is built weekly by this repo's "Romhack index" workflow.
 *
 * RetroAchievements recognises a hack by the checksum of the patched ROM, and keeps the
 * patch that produces it in its RAPatches repository. So the whole loop is a lookup and a
 * patch: a base ROM's CRC finds the hacks made for it, our patcher applies one (verifying the
 * base is right, since BPS carries the source checksum), and the result is a ROM the site
 * recognises, achievements and all.
 *
 * We host only the index, keyed by the base ROM's CRC (`ra-patches/<shortname>.json`,
 * generated by the bot from the repo so it updates without an app build). The patch files
 * stay RetroAchievements' to serve: they are fetched from their repo at apply time, which
 * also keeps redistribution their concern rather than ours. Re-checked each use, since hacks are
 * added constantly; a platform with no index simply offers no hacks.
 */
object RaPatches {

    // Published by this repo's "Romhack index" workflow (tools/build_rapatches.py) to the data
    // branch. It used to live in chameleon-data, which is private, so the app couldn't read it.
    private const val IndexUrl =
        "https://raw.githubusercontent.com/JoeysRetroHandhelds/JoeyOS/data/ra-patches/"
    private const val PatchRepo =
        "https://raw.githubusercontent.com/RetroAchievements/RAPatches/main/"

    @Volatile
    var cacheDir: File? = null

    // The index is republished within minutes of a new hack (the workflow checks RAPatches every
    // 15 minutes), so the app asks for it again whenever it's used, via ETag: an unchanged index
    // costs a bodyless 304, and offline the copy on disk is used. Within one short visit (a few
    // minutes) the parsed table is reused rather than re-asked for every screen.
    private const val ReuseForMillis = 5L * 60 * 1000

    // Per platform: crc -> the hacks made for the ROM with that checksum, and when it was loaded.
    private val loaded = ConcurrentHashMap<String, Map<String, List<RaHack>>>()
    private val loadedAt = ConcurrentHashMap<String, Long>()
    private val absent = ConcurrentHashMap.newKeySet<String>()

    /**
     * Whether the index for [shortname] could be loaded (downloaded now, or cached from before).
     * False means the list itself is unreachable, which the tool reports differently from
     * "none of your games have hacks".
     */
    suspend fun indexAvailable(shortname: String): Boolean = tableFor(shortname.lowercase()) != null

    /** Forget that [shortname]'s index was unreachable, so the next lookup tries the network again. */
    fun retry(shortname: String) { absent -= shortname.lowercase() }

    /** The hacks known for [crc32] on [packShortname], newest-source-first as published. */
    suspend fun hacksFor(packShortname: String, crc32: String): List<RaHack> {
        val table = tableFor(packShortname.lowercase()) ?: return emptyList()
        return table[normaliseCrc(crc32)].orEmpty()
    }

    private fun recent(shortname: String): Map<String, List<RaHack>>? =
        loaded[shortname]?.takeIf { System.currentTimeMillis() - (loadedAt[shortname] ?: 0) < ReuseForMillis }

    private suspend fun tableFor(shortname: String): Map<String, List<RaHack>>? {
        recent(shortname)?.let { return it }
        if (shortname in absent) return null
        return withContext(Dispatchers.IO) {
            recent(shortname)?.let { return@withContext it }
            val cacheFile = file(shortname) ?: return@withContext null
            // Always re-checked with an ETag, so an unchanged index costs a 304 rather than a
            // download. Offline, the copy on disk is used so the tool still works.
            val json = ConditionalFetch.text("$IndexUrl$shortname.json", cacheFile, etagFile(shortname))
                ?: cacheFile.takeIf { it.isFile }?.let { runCatching { it.readText() }.getOrNull() }
            if (json == null) {
                absent += shortname
                return@withContext null
            }
            val parsed = runCatching { parse(json) }.getOrNull()
            if (parsed == null) {
                absent += shortname
                null
            } else {
                loaded[shortname] = parsed
                loadedAt[shortname] = System.currentTimeMillis()
                AppLog.i("RomHacks", "ra-patches: $shortname ${parsed.values.sumOf { it.size }} hacks")
                parsed
            }
        }
    }

    /**
     * The consoles the index covers (one `ra-patches/<name>.json` each) and the ROM folder names
     * people use for them. JoeyOS reads `ROMs/<folder>` directly, so a console is found under any
     * of its common names, case-insensitively.
     */
    val Consoles: List<Pair<String, Set<String>>> = listOf(
        "nes", "fds", "snes", "n64", "gb", "gbc", "gba", "nds", "genesis", "gamegear", "sega32x",
        "segacd", "saturn", "dreamcast", "tg16", "pcfx", "neogeocd", "msx", "3do", "gc", "wii",
        "ps2", "psp", "psx",
    ).map { it to RomFolders.namesFor(it) } + listOf(
        // The index names Master System "master", and has one file for both Neo Geo Pockets.
        "master" to RomFolders.namesFor("mastersystem"),
        "ngp" to RomFolders.namesFor("ngp") + RomFolders.namesFor("ngpc"),
    )

    /** Each covered console's `ROMs/<folder>` folders on every storage volume. */
    fun romFolders(roots: List<File>): Map<String, List<File>> =
        RomFolders.group(roots, Consoles) { it.second }.mapKeys { it.key.first }

    fun normaliseCrc(crc32: String): String =
        crc32.trim().lowercase().removePrefix("0x").padStart(8, '0').takeLast(8)

    fun parse(json: String): Map<String, List<RaHack>> {
        val o = JSONObject(json)
        return o.keys().asSequence().associate { crc ->
            val arr = o.getJSONArray(crc)
            normaliseCrc(crc) to (0 until arr.length()).map { i ->
                val h = arr.getJSONObject(i)
                RaHack(
                    name = h.getString("name"),
                    type = h.optString("type", "Hack"),
                    path = h.getString("path"),
                    format = h.optString("format", h.getString("path").substringAfterLast('.')).lowercase(),
                )
            }
        }
    }

    /**
     * The base ROM's checksum, the way No-Intro and RetroAchievements list it: for a zipped
     * ROM, the CRC the archive already stores for the file inside, so a compressed library
     * matches too without unpacking.
     */
    fun crcOf(file: File): String? = runCatching {
        if (file.extension.equals("zip", ignoreCase = true)) {
            ZipFile(file).use { zip ->
                val entry = zip.entries().asSequence()
                    .filterNot { it.isDirectory }
                    .maxByOrNull { it.size }
                entry?.crc?.takeIf { it >= 0 }?.let { return "%08x".format(it) }
            }
        }
        val crc = CRC32()
        file.inputStream().buffered().use { ins ->
            val buffer = ByteArray(1 shl 16)
            while (true) {
                val read = ins.read(buffer)
                if (read < 0) break
                crc.update(buffer, 0, read)
            }
        }
        "%08x".format(crc.value)
    }.getOrNull()

    /**
     * The base ROM to patch: for a loose file, itself; for a zipped one, the ROM inside,
     * since that is what the checksum matched and what the patch expects. Returns the inner
     * file name (so the hack can be named and given the right extension) and its bytes.
     */
    /** The name of the game inside [file] (the largest entry of a zip), without reading it. */
    fun baseRomName(file: File): String =
        if (file.extension.equals("zip", ignoreCase = true)) runCatching {
            ZipFile(file).use { zip ->
                zip.entries().asSequence().filterNot { it.isDirectory }.maxByOrNull { it.size }
                    ?.name?.substringAfterLast('/')
            }
        }.getOrNull() ?: file.name
        else file.name

    fun baseRom(file: File): Pair<String, ByteArray>? = runCatching {
        if (file.extension.equals("zip", ignoreCase = true)) {
            ZipFile(file).use { zip ->
                val entry = zip.entries().asSequence()
                    .filterNot { it.isDirectory }
                    .maxByOrNull { it.size } ?: return null
                zip.getInputStream(entry).use { entry.name.substringAfterLast('/') to it.readBytes() }
            }
        } else {
            file.name to file.readBytes()
        }
    }.getOrNull()

    /**
     * Downloads a hack's patch and returns the patch bytes, unwrapping a zip or 7z the repo
     * stored it in. Null on any failure, so the caller reports "could not fetch" rather than
     * applying nothing.
     */
    suspend fun downloadPatch(hack: RaHack): ByteArray? = withContext(Dispatchers.IO) {
        val bytes = fetchBytes(PatchRepo + encodePath(hack.path)) ?: return@withContext null
        when (hack.path.substringAfterLast('.').lowercase()) {
            "zip" -> firstPatchInZip(bytes)
            "7z" -> firstPatchIn7z(bytes)
            else -> bytes
        }
    }

    private val PatchExtensions = setOf("bps", "ips", "ups", "xdelta", "xdelta3", "vcdiff")

    private fun firstPatchInZip(archive: ByteArray): ByteArray? = runCatching {
        ZipInputStream(archive.inputStream()).use { zis ->
            while (true) {
                val entry = zis.nextEntry ?: break
                if (!entry.isDirectory &&
                    entry.name.substringAfterLast('.').lowercase() in PatchExtensions
                ) {
                    return@use zis.readBytes()
                }
            }
            null
        }
    }.getOrNull()

    private fun firstPatchIn7z(archive: ByteArray): ByteArray? = runCatching {
        val temp = File.createTempFile("rapatch", ".7z")
        try {
            temp.writeBytes(archive)
            SevenZFile.builder().setFile(temp).get().use { sevenZ ->
                var entry = sevenZ.nextEntry
                while (entry != null) {
                    if (!entry.isDirectory &&
                        entry.name.substringAfterLast('.').lowercase() in PatchExtensions
                    ) {
                        return@use sevenZ.getInputStream(entry).readBytes()
                    }
                    entry = sevenZ.nextEntry
                }
                null
            }
        } finally {
            temp.delete()
        }
    }.getOrNull()

    /** Each path segment encoded, so spaces and parentheses in a hack's name survive. */
    private fun encodePath(path: String): String =
        path.split('/').joinToString("/") { URLEncoder.encode(it, "UTF-8").replace("+", "%20") }

    private fun fetchBytes(url: String): ByteArray? = runCatching {
        Http.get(url, connectMs = 15_000, readMs = 60_000).bytes
    }.getOrNull()

    private fun file(shortname: String) = cacheDir?.let { File(it, "ra-patches/$shortname.json") }

    private fun etagFile(shortname: String) = File(cacheDir, "ra-patches/$shortname.etag")
}
